# Generated by Django 6.0 on 2026-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doccoon", "0003_doccoonpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doccoon",
            name="year",
            field=models.IntegerField(max_length=4),
        ),
    ]
