# Generated by Django 6.0 on 2026-01-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doccoon", "0004_alter_doccoon_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="doccoon",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Published", "Published"),
                    ("Deleted", "Deleted"),
                ],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="doccoon",
            name="year",
            field=models.IntegerField(),
        ),
    ]
