# Generated by Django 6.0 on 2026-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0007_usersettings_profile_visible_usersettings_theme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderkey',
            name='api_key',
            field=models.TextField(),
        ),
    ]
