# Generated by Django 6.0 on 2026-01-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0008_alter_aiproviderkey_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccoonpage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
