# Generated by Django 6.0 on 2026-01-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0009_alter_doccoonpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ai_model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1', 'GPT-4.1'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.5-flash-preview-05-20', 'Gemini 2.5 Flash'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro')], default='gpt-4o-mini', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='auto_save_interval',
            field=models.IntegerField(default=2),
        ),
    ]
