# Generated by Django 6.0 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0010_usersettings_ai_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='ai_model',
        ),
        migrations.AddField(
            model_name='aiproviderkey',
            name='model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('gpt-4.1-nano', 'GPT-4.1 Nano'), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1', 'GPT-4.1'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], default='gpt-4o-mini', max_length=50),
        ),
    ]
