# Generated by Django 6.0 on 2026-02-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0011_remove_usersettings_ai_model_aiproviderkey_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpage',
            name='content_snapshot',
            field=models.TextField(blank=True, default=''),
        ),
    ]
