# Generated by Django 6.0 on 2026-02-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0012_sharedpage_content_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedbook',
            name='pages_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
