# Generated by Django 6.0 on 2026-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0014_encrypt_existing_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='layout_mode',
            field=models.CharField(choices=[('book', 'Book'), ('page', 'Page')], default='book', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='live_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='view_mode',
            field=models.BooleanField(default=False),
        ),
    ]
