# Generated by Django 6.0 on 2026-02-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0015_usersettings_layout_mode_usersettings_live_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doccoon',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
