# Generated by Django 6.0 on 2026-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doccoon', '0016_make_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('github', 'GitHub')], default='email', max_length=10),
        ),
    ]
